name: tasktrek
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0-323.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  sqflite: ^2.3.0
  path: ^1.9.0
  supabase_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/user.png
    - lib/assets/images/padlock.png
    - lib/assets/images/Brgy. Sphere Card Illustration.png
    - lib/assets/images/Frame 117.png
    - lib/assets/images/Frame 149.png
    - lib/assets/images/Union.png
    - lib/assets/images/Group 187.png
